# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # 5AM (PT) daily
    - cron:  '0 13 * * *'

permissions:
  contents: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Run setup_db
    #   run: python setup_db.py
    # - uses: stefanzweifel/git-auto-commit-action@v5
    # - id: 'auth'
    #   name: 'Authenticate to Google Cloud'
    #   uses: 'google-github-actions/auth@v1'
    #   with:
    #     workload_identity_provider: 'projects/910382441474/locations/global/workloadIdentityPools/github-actions-pool/providers/my-provider'
    #     service_account: 'example-app-sa@precise-cabinet-280004.iam.gserviceaccount.com'
    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up Cloud SDK'
      uses:  google-github-actions/setup-gcloud@v0
      with:
        version: '275.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy Latest Datasette instance
      run: |-
        gcloud config set run/region us-west1
        gcloud config set project precise-cabinet-280004
        datasette publish cloudrun nfl.db --service nfl-datasette --static -:static